//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRProcat
    {
        public int ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> AutoID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<int> PriceByDay { get; set; }
        public Nullable<int> ProcatPrice { get; set; }
    
        public virtual PRAuto PRAuto { get; set; }
        public virtual PRClient PRClient { get; set; }
    }
}
